### ISSUE TITLE
Support for bpmnlint v7. Update peer dependency to support v7.

### ISSUE THREAD

**Issue by fabio-bertone** [nikku/bpmnlint-loader#3]
__What should we do?__

Do you have plans to bump the peer dependency of bpmnlint to v7? This would be helpful to keep all bpmn libraries up-to-date.

__Why should we do it?__

There's currently development work being done to bpmnlint and this is a dependency to load bpmnlint configuration into any project. It makes sense to keep this in line so users pulling in these libraries can pull down the latest of each without running into peer dependency warnings.

**Comment by nikku** [comment]
Happy to look into a PR, if you file one.

If you bump the peer depdendency, please update the responding test dependency, too.

**Comment by nikku** [comment]
I can look into the PR later tonight and merge it.
